/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UKeySetDialog.java
 *
 * Created on 2011-6-7, 22:00:43
 */
package org.jhrcore.client;

import com.foundercy.pf.control.table.FTable;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ButtonGroup;
import org.jhrcore.entity.A01;
import org.jhrcore.entity.A01PassWord;
import org.jhrcore.entity.DeptCode;
import org.jhrcore.entity.SysParameter;
import org.jhrcore.entity.base.TempFieldInfo;
import org.jhrcore.rebuild.EntityBuilder;
import org.jhrcore.ui.action.CloseAction;

/**
 *
 * @author zhongzhao
 */
public class UKeySetDialog extends javax.swing.JDialog {

    public static SysParameter useUkey_para = null;
    private FTable ftA01;

    /** Creates new form UKeySetDialog */
    public UKeySetDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initOthers();
        setupEvents();
    }

    private void initOthers() {
        setTitle("UKey 设置");

        useUkey_para = (SysParameter) CommUtil.fetchEntityBy("from SysParameter sp where sp.sysParameter_key = 'System.use_ukey' ");
        if (useUkey_para == null) {
            useUkey_para = new SysParameter();
            useUkey_para.setSysParameter_key("System.use_ukey");
            useUkey_para.setSysparameter_code("UseUkey");
            useUkey_para.setSysparameter_name("是否启动UKey");
            useUkey_para.setSysparameter_value("0");

            CommUtil.saveOrUpdate(useUkey_para);
        }

        ButtonGroup bg = new ButtonGroup();
        bg.add(rbAll);
        bg.add(rbSelected);

        ftA01 = new FTable(A01PassWord.class, true, true, false, "UKeySetDialog");
        List<TempFieldInfo> listAll = new ArrayList();
        List<TempFieldInfo> listDefault = new ArrayList();
        for (TempFieldInfo tfi : EntityBuilder.getCommFieldInfoListOf(DeptCode.class, EntityBuilder.COMM_FIELD_VISIBLE)) {
            listAll.add(tfi);
            if ("dept_full_name".equals(tfi.getField_name())) {
                listDefault.add(tfi);
            }

            tfi.setField_name("a01.deptCode." + tfi.getField_name());
        }
        for (TempFieldInfo tfi : EntityBuilder.getCommFieldInfoListOf(A01.class, EntityBuilder.COMM_FIELD_VISIBLE)) {
            listAll.add(tfi);
            if ("a0101".equals(tfi.getField_name()) || "a0190".equals(tfi.getField_name())) {
                listDefault.add(tfi);
            }

            tfi.setField_name("a01." + tfi.getField_name());
        }
        ftA01.setAll_fields(listAll, listDefault, new ArrayList(), "UKeySetDialog");
        pnlSelectedPerson.add(ftA01, BorderLayout.CENTER);

        refreshUI("1".equals(useUkey_para.getSysparameter_value()));
    }

    private void setupEvents() {
        cbUKeyUsed.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                useUkey_para.setSysparameter_value(cbUKeyUsed.isSelected() ? "1" : "0");
                CommUtil.updateEntity(useUkey_para);

                refreshUI("1".equals(useUkey_para.getSysparameter_value()));
            }
        });

        rbAll.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {

                refreshUI("1".equals(useUkey_para.getSysparameter_value()));
            }
        });

        rbSelected.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {

                refreshUI("1".equals(useUkey_para.getSysparameter_value()));
            }
        });

        btnAdd.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
            }
        });

        btnRemove.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
            }
        });

        btnOK.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
            }
        });

        CloseAction.doCloseAction(btnCancel);
    }

    private void refreshUI(boolean isUsed) {
        cbUKeyUsed.setSelected(isUsed);

        rbAll.setEnabled(isUsed);
        rbSelected.setEnabled(isUsed);

        btnAdd.setEnabled(isUsed && rbSelected.isSelected());
        btnRemove.setEnabled(isUsed && rbSelected.isSelected());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbUKeyUsed = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        rbAll = new javax.swing.JRadioButton();
        rbSelected = new javax.swing.JRadioButton();
        pnlSelectedPerson = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnOK = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cbUKeyUsed.setText("是否启用");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("设置适用对象"));

        rbAll.setSelected(true);
        rbAll.setText("全部角色人员");

        rbSelected.setText("选择角色人员");

        pnlSelectedPerson.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlSelectedPerson.setLayout(new java.awt.BorderLayout());

        btnAdd.setText("添加");

        btnRemove.setText("移除");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbAll)
                    .addComponent(rbSelected)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(pnlSelectedPerson, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAdd)
                            .addComponent(btnRemove))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(rbAll)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbSelected)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlSelectedPerson, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(btnAdd)
                        .addGap(37, 37, 37)
                        .addComponent(btnRemove)))
                .addContainerGap())
        );

        btnOK.setText("确定");

        btnCancel.setText("取消");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(cbUKeyUsed))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(btnOK)
                        .addGap(135, 135, 135)
                        .addComponent(btnCancel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbUKeyUsed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnOK))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                UKeySetDialog dialog = new UKeySetDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnRemove;
    private javax.swing.JCheckBox cbUKeyUsed;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlSelectedPerson;
    private javax.swing.JRadioButton rbAll;
    private javax.swing.JRadioButton rbSelected;
    // End of variables declaration//GEN-END:variables
}
