/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NoticePanel1.java
 *
 * Created on 2010-1-26, 19:03:07
 */
package org.jhrcore.client.system;

import chrriis.dj.nativeswing.swtimpl.NativeInterface;
import chrriis.dj.nativeswing.swtimpl.components.JWebBrowser;
import java.awt.BorderLayout;
import javax.swing.SwingUtilities;
import org.jhrcore.client.CommUtil;
import org.jhrcore.client.UserContext;
import org.jhrcore.ui.task.IModulePanel;

/**
 *
 * @author mxliteboss
 */
public class SysNoticePanel extends javax.swing.JPanel implements IModulePanel {

    private String url = "http://localhost:8080/";
    public static final String module_code = "SysNotice";

    /** Creates new form NoticePanel1 */
    public SysNoticePanel() {
        initComponents();
        initOthers();
    }

    private void initOthers() {
        String right = "";
        if (UserContext.hasFunctionRight(module_code + ".addNotice")) {
            right += "1";
        } else {
            right += "0";
        }
        if (UserContext.hasFunctionRight(module_code + ".editNotice")) {
            right += "1";
        } else {
            right += "0";
        }
        if (UserContext.hasFunctionRight(module_code + ".delNotice")) {
            right += "1";
        } else {
            right += "0";
        }
        url = "http://" + CommUtil.getWebServerIp() + ":" + CommUtil.getWebServerPort() + "/webhr/customer/notice/enterNotice.do?right=" + right;
        NativeInterface.open();
        SwingUtilities.invokeLater(new Runnable() {

            @Override
            public void run() {
                JWebBrowser webBrowser = new JWebBrowser();
                webBrowser.setBarsVisible(false);
                webBrowser.navigate(url); // ÍøÖ·Ê×Ò³
                add(webBrowser, BorderLayout.CENTER);
            }
        });
        NativeInterface.runEventPump();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    @Override
    public void setFunctionRight() {
    }

    @Override
    public void pickClose() {
    }

    @Override
    public void refresh() {
    }

    @Override
    public String getModuleCode() {
        return module_code;
    }
}
