/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RegisterQuestDialog.java
 *
 * Created on 2011-7-11, 20:41:15
 */

package org.jhrcore.client.personnel.register;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import org.jhrcore.client.UserContext;
import org.jhrcore.ui.task.IModuleCode;

/**
 *
 * @author hflj
 */
public class RegisterQuestDialog extends javax.swing.JDialog implements IModuleCode{
    private boolean click_ok = false;
    private int result =0 ;
    private boolean dogo;
    private String module_code = "EmpRegister.btnEdit.tFieldCardNo";
    public RegisterQuestDialog(String title,boolean dogo){
        this.setTitle(title);
        this.dogo = dogo;
        initComponents();
        setupEvents();
    }
    /** Creates new form RegisterQuestDialog */
    public RegisterQuestDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public RegisterQuestDialog() {
        initComponents();
        setupEvents();
    }
    
    
    private void setupEvents(){
        btnOk.addActionListener(new ActionListener(){

            @Override
            public void actionPerformed(ActionEvent e) {
                result = 1;
                click_ok = true;
                dispose();
            }

        });
        btnView.addActionListener(new ActionListener(){

            @Override
            public void actionPerformed(ActionEvent e) {
                result = 2;
                click_ok = true;
                dispose();
            }

        });
        btnCancel.addActionListener(new ActionListener(){

            @Override
            public void actionPerformed(ActionEvent e) {
                result = 0;
                dispose();
            }

        });
        this.btnOk.setEnabled(UserContext.isSA||dogo);
    }

    public boolean isClick_ok() {
        return click_ok;
    }

    public int getResult() {
        return result;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOk = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);

        btnOk.setText("继续录入");

        btnView.setText("查看人员");

        btnCancel.setText("取消");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnOk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnView)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancel)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk)
                    .addComponent(btnView)
                    .addComponent(btnCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RegisterQuestDialog dialog = new RegisterQuestDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnView;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getModuleCode() {
        return module_code;
    }

}
