/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MySingleToolTipPanel.java
 *
 * Created on 2013-10-9, 11:00:42
 */
package org.jhrcore.client.desk;

import com.foundercy.pf.control.table.FTable;
import java.util.ArrayList;
import java.util.List;
import org.jhrcore.client.CommUtil;
import org.jhrcore.client.report.ReportPanel;
import org.jhrcore.ui.HrTextPane;

/**
 *
 * @author mxliteboss
 */
public class MySingleToolTipPanel extends javax.swing.JPanel {

    private static MySingleToolTipPanel pnlTip = null;
    private HrTextPane textPane = new HrTextPane();
    private FTable ftable;

    /** Creates new form MySingleToolTipPanel */
    public MySingleToolTipPanel() {
        initComponents();
        initOthers();
    }

    public static MySingleToolTipPanel getInstance(String msg, String formula) {
        if (pnlTip == null) {
            pnlTip = new MySingleToolTipPanel();
        }
        pnlTip.refreshUI(msg, formula);
        return pnlTip;
    }

    private void initOthers() {
        pnlMsg.add(textPane);
    }

    private void refreshUI(String msg, String formula) {
        textPane.setText(msg);
        String sql = ReportPanel.getNewQuery(formula, null);
        List list = CommUtil.selectSQL(sql, true);
        List list_head = new ArrayList();
        String[] objs = (String[]) list.get(0);
        for (String head : objs) {
            list_head.add(head);
        }
        ftable = new FTable(list_head);
        ftable.setRight_allow_flag(true);
        ftable.removeAllFunItems();
        list.remove(0);
        ftable.setObjects(list);
        pnlData.removeAll();
        pnlData.add(ftable);
        pnlData.updateUI();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        pnlMsg = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        pnlData = new javax.swing.JPanel();

        jLabel1.setText("提示内容");

        pnlMsg.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("数据内容");

        pnlData.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlData.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE))
            .addComponent(pnlMsg, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE))
            .addComponent(pnlData, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlData, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel pnlData;
    private javax.swing.JPanel pnlMsg;
    // End of variables declaration//GEN-END:variables
}
