/*
 * FunctionModifyMngPanel.java
 *
 * Created on 2008年9月29日, 上午11:08
 */
package org.jhrcore.client.system.right;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.TreePath;
import org.jhrcore.client.CommUtil;
import org.jhrcore.util.SysUtil;
import org.jhrcore.client.UserContext;
import org.jhrcore.util.UtilTool;
import org.jhrcore.entity.right.FuntionRight;
import org.jhrcore.entity.salary.ValidateSQLResult;
import org.jhrcore.msg.CommMsg;
import org.jhrcore.ui.BeanPanel;
import org.jhrcore.ui.ContextManager;
import org.jhrcore.ui.task.IModulePanel;
import org.jhrcore.util.ComponentUtil;
import org.jhrcore.util.MsgUtil;

/**

 * @author  yangzhou
 */
public class FuntionModifyMngPanel extends JPanel implements IModulePanel {

    private JButton btnAdd = new JButton("新增功能");
    private JButton btnEdit = new JButton("修改功能名称");
    private JButton btnCanedit = new JButton("取消编辑");
    private JButton btnDel = new JButton("删除");
    private JButton btnSave = new JButton("保存");
    private boolean canModify = false;
    private FuntionRight cur_funtionRight;
    private FuntionModifyPanel funtionModifyPanel;
    private BeanPanel beanPanel = new BeanPanel();
    private DefaultMutableTreeNode cur_node;
    public static final String module_code = "SysFuntionModify";

    /** Creates new form FunctionModifyMngPanel */
    public FuntionModifyMngPanel() {
        initComponents();
        initOthers();
        setupEvents();
    }

    @Override
    public void setFunctionRight() {
        btnDel.setVisible(UserContext.isSA);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        leftPanel = new javax.swing.JPanel();
        rightPanel = new javax.swing.JPanel();
        toolbar = new javax.swing.JToolBar();
        pnlMain = new javax.swing.JPanel();

        leftPanel.setPreferredSize(new java.awt.Dimension(200, 0));
        leftPanel.setLayout(new java.awt.BorderLayout());
        jSplitPane1.setLeftComponent(leftPanel);

        toolbar.setFloatable(false);
        toolbar.setRollover(true);

        pnlMain.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolbar, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addComponent(toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(rightPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JToolBar toolbar;
    // End of variables declaration//GEN-END:variables

    private void initOthers() {
        toolbar.add(btnEdit);
        toolbar.add(btnCanedit);
        toolbar.add(btnSave);
        toolbar.add(btnDel);
        beanPanel.setColumns(1);
        List<String> disable_fields = new ArrayList<String>();
        disable_fields.add("fun_code");
        disable_fields.add("fun_parent_code");
        disable_fields.add("fun_module_flag");
        beanPanel.setDisable_fields(disable_fields);
        pnlMain.add(beanPanel, BorderLayout.CENTER);
        funtionModifyPanel = new FuntionModifyPanel();
        leftPanel.add(funtionModifyPanel, BorderLayout.CENTER);
        btnCanedit.setEnabled(false);
    }

    private void setupEvents() {
        funtionModifyPanel.getFunTree().addTreeSelectionListener(new TreeSelectionListener() {

            @Override
            public void valueChanged(TreeSelectionEvent e) {
                Object obj = e.getPath().getLastPathComponent();
                if (obj == null) {
                    return;
                }
                if (obj instanceof DefaultMutableTreeNode) {
                    cur_node = (DefaultMutableTreeNode) obj;
                    Object tmp_cur_funtionRight = cur_node.getUserObject();
                    if (tmp_cur_funtionRight instanceof FuntionRight) {
                        cur_funtionRight = (FuntionRight) tmp_cur_funtionRight;
                        changRightPanel(cur_funtionRight, canModify);
                    }
                }

            }
        });// 添加到数据中去,点选节点事件
        btnAdd.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                addObject();
            }
        });
        btnDel.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                delObject();
            }
        });
        btnEdit.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                canModify = true;
                changRightPanel(cur_funtionRight, canModify);
            }
        });
        btnCanedit.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                canModify = false;
                changRightPanel(cur_funtionRight, canModify);
            }
        });
        btnSave.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                saveObject();
                changRightPanel(cur_funtionRight, canModify);
            }
        });
        Object obj = funtionModifyPanel.getFunTree().getLastSelectedPathComponent();
        if (obj instanceof DefaultMutableTreeNode) {
            cur_node = (DefaultMutableTreeNode) obj;
            changRightPanel(((DefaultMutableTreeNode) obj).getUserObject(), canModify);
        }
    }

    private void addObject() {
        DefaultMutableTreeNode parent = (DefaultMutableTreeNode) funtionModifyPanel.getFunTree().getLastSelectedPathComponent();
        FuntionRight funtionRight = (FuntionRight) UtilTool.createUIDEntity(FuntionRight.class);
        Object obj = parent.getUserObject();
        if (obj instanceof FuntionRight) {
            funtionRight.setFun_code(SysUtil.getNewFuntionCode(cur_funtionRight.getFun_code()));
            funtionRight.setFun_parent_code(cur_funtionRight.getFun_code());
            funtionRight.setFun_level(cur_funtionRight.getFun_level() + 1);
        } else {
            funtionRight.setFun_level(0);
            funtionRight.setFun_code("1");
            funtionRight.setFun_parent_code("ROOT");
        }
        if (BeanPanel.edit(funtionRight)) {
            CommUtil.saveEntity(funtionRight);
            parent.add(new DefaultMutableTreeNode(funtionRight));
            funtionModifyPanel.getFunTree().updateUI();
        }

    }

    private void saveObject() {
        if (cur_node == null) {
            return;
        }
        if (cur_funtionRight != null) {
            DefaultMutableTreeNode node = cur_node;
            ValidateSQLResult result = CommUtil.updateEntity(cur_funtionRight);
            if (result.getResult() == 0) {
                FuntionRight fr = UserContext.getFuntion_keys().get(cur_funtionRight.getFun_module_flag());
                if (fr != null) {
                    fr.setFun_name(cur_funtionRight.getFun_name());
                    UserContext.getFuntion_keys().put(cur_funtionRight.getFun_module_flag(), fr);
                }
                MsgUtil.showHRSaveSuccessMsg(ContextManager.getMainFrame());
                node.setUserObject(cur_funtionRight);
                funtionModifyPanel.getFunTree().getSelectionModel().clearSelection();
                funtionModifyPanel.getFunTree().addSelectionPath(new TreePath(node.getPath()));
                funtionModifyPanel.getFunTree().updateUI();
            } else {
                MsgUtil.showErrorMsg(CommMsg.SAVEFAIL);
            }
        }
    }

    private void changRightPanel(Object obj, boolean canModify) {
        if (obj instanceof FuntionRight) {
            cur_funtionRight = (FuntionRight) obj;
        } else {
            cur_funtionRight = null;
            return;
        }
        ComponentUtil.setCompEnable(this, btnEdit, !canModify);
        ComponentUtil.setCompEnable(this, btnCanedit, canModify);
        ComponentUtil.setCompEnable(this, btnSave, canModify);
        beanPanel.setBean(cur_funtionRight);
        beanPanel.setEditable(canModify);
        beanPanel.bind();
        rightPanel.updateUI();
        toolbar.updateUI();
    }

    private void delObject() {
        if (cur_node == null) {
            return;
        }
        if (cur_node.getUserObject() instanceof FuntionRight) {
            if (MsgUtil.showNotConfirmDialog("确定要删除当前选择功能菜单吗?")) {
                return;
            }
            DefaultMutableTreeNode parent = (DefaultMutableTreeNode) cur_node.getParent();
            DefaultMutableTreeNode node = cur_node.getPreviousSibling();
            if (node == null) {
                node = (DefaultMutableTreeNode) cur_node.getParent();
            }
            parent.remove(cur_node);
            if (cur_funtionRight != null) {
                CommUtil.deleteEntity(cur_funtionRight);
            }
            funtionModifyPanel.getFunTree().getSelectionModel().clearSelection();
            funtionModifyPanel.getFunTree().addSelectionPath(new TreePath(node.getPath()));
            funtionModifyPanel.getFunTree().updateUI();
        }
    }

    @Override
    public void pickClose() {
    }

    @Override
    public void refresh() {
    }

    @Override
    public String getModuleCode() {
        return module_code;
    }
}
