/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddLeaveManyDayDialog.java
 *
 * Created on 2009-11-30, 14:24:36
 */
package org.jhrcore.client.ecard.leave;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.Hashtable;
import java.util.List;
import javax.swing.JScrollPane;
import org.jhrcore.client.CommUtil;
import org.jhrcore.util.DateUtil;
import org.jhrcore.util.PublicUtil;
import org.jhrcore.util.UtilTool;
import org.jhrcore.entity.base.TempFieldInfo;
import org.jhrcore.entity.ecard.Ecard_leave;
import org.jhrcore.entity.salary.ValidateSQLResult;
import org.jhrcore.rebuild.EntityBuilder;
import org.jhrcore.ui.BeanPanel;
import org.jhrcore.ui.task.IModuleCode;
import org.jhrcore.ui.JhrDatePicker;
import org.jhrcore.ui.action.CloseAction;
import org.jhrcore.util.MsgUtil;

/**
 *
 * @author mxliteboss
 */
public class AddLeaveManyDayDialog extends javax.swing.JDialog implements IModuleCode {

    private JhrDatePicker jdpStart = new JhrDatePicker();
    private JhrDatePicker jdpEnd = new JhrDatePicker();
    private boolean click_ok = false;
    private ValidateSQLResult result;
    private Ecard_leave k_leave_new;
    private BeanPanel beanPanel;
    private List fields = new ArrayList();
    public static final String module_code = "Ecard_leave.miAddManyDay";

    public boolean isClick_ok() {
        return click_ok;
    }

    public ValidateSQLResult getResult() {
        return result;
    }

    /** Creates new form AddLeaveManyDayDialog */
    public AddLeaveManyDayDialog(java.awt.Frame parent) {
        super(parent);
        this.setTitle("多日连续增加");
        initComponents();
        initOthers();
        setupEvents();
    }

    public AddLeaveManyDayDialog() {
        this.setTitle("多日连续增加");
        initComponents();
        initOthers();
        setupEvents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        btnOk = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pnlMain = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);

        btnOk.setText("确定");

        btnCancel.setText("取消");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(277, Short.MAX_VALUE)
                .addComponent(btnOk)
                .addGap(43, 43, 43)
                .addComponent(btnCancel)
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancel)
                    .addComponent(btnOk))
                .addContainerGap())
        );

        jPanel4.setPreferredSize(new java.awt.Dimension(474, 122));

        jLabel3.setText("开始日期");

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel7.setText("（含此日）");

        jLabel8.setText("（含此日）");

        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel6.setText("结束日期");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pnlMain.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel pnlMain;
    // End of variables declaration//GEN-END:variables

    private void initOthers() {
        jPanel2.add(jdpStart, BorderLayout.CENTER);
        jPanel3.add(jdpEnd, BorderLayout.CENTER);
        k_leave_new = (Ecard_leave) UtilTool.createUIDEntity(Ecard_leave.class);
        
        beanPanel = new BeanPanel();
        beanPanel.setColumns(1);
        pnlMain.add(new JScrollPane(beanPanel), BorderLayout.CENTER);
        List<TempFieldInfo> leave_infos = EntityBuilder.getCommFieldInfoListOf(Ecard_leave.class, EntityBuilder.COMM_FIELD_VISIBLE);

        for (TempFieldInfo tfi : leave_infos) {
            if (tfi.getField_name().equalsIgnoreCase("Ecard_leave_date")) {
                continue;
            }
            fields.add(tfi.getField_name());
        }
        beanPanel.setBean(k_leave_new);
        beanPanel.setFields(fields);
        beanPanel.setEditable(true);
        beanPanel.bind();
    }

    private void setupEvents() {
        CloseAction.doCloseAction(btnCancel);
        btnOk.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                String k_name = k_leave_new.getEcard_leave_name();
                if (k_name == null || k_name.trim().equals("")) {
                    MsgUtil.showInfoMsg("请输入休息日名称");
                    return;
                }
                Date startDate = jdpStart.getDate();
                Date endDate = jdpEnd.getDate();
                if (startDate.after(endDate)) {
                    MsgUtil.showInfoMsg("结束日期不能早于开始日期");
                    return;
                }
                String startTime = DateUtil.toStringForQuery(startDate);
                String endTime = DateUtil.toStringForQuery(endDate);
                String hql = "from Ecard_leave k where 1=1";
                hql = hql + " and k.k_leave_date>= " + startTime + " and k.k_leave_date<= " + endTime;
                List exist_list = CommUtil.fetchEntities(hql);
                Hashtable<String, Ecard_leave> exist_keys = new Hashtable<String, Ecard_leave>();
                for (Object obj : exist_list) {
                    Ecard_leave k_leave = (Ecard_leave) obj;
                    exist_keys.put(DateUtil.DateToStr(k_leave.getEcard_leave_date()), k_leave);
                }
                List<String> all_dates = new ArrayList<String>();
                all_dates.add(DateUtil.DateToStr(startDate));
                Calendar c = Calendar.getInstance();
                c.setTime(startDate);
                while (c.getTime().before(endDate)) {
                    String day = DateUtil.DateToStr(c.getTime());
                    if (!all_dates.contains(day)) {
                        all_dates.add(day);
                    }
                    c.add(Calendar.DAY_OF_MONTH, 1);
                }
                String day = DateUtil.DateToStr(c.getTime());
                if (!all_dates.contains(day)) {
                    all_dates.add(day);
                }
                
                List saveList = new ArrayList();
                for (String tmp : all_dates) {
                    Ecard_leave k_leave = exist_keys.get(tmp);
                    if (k_leave == null) {
                        k_leave = (Ecard_leave) UtilTool.createUIDEntity(Ecard_leave.class);
                    } else {
                        continue;
                    }
                    PublicUtil.copyProperties(k_leave_new, k_leave, fields, fields);
                    saveList.add(k_leave);
                    k_leave.setEcard_leave_name(k_name);
                    k_leave.setEcard_leave_date(DateUtil.StrToDate(tmp));
                }
                result = CommUtil.saveList(saveList);
                click_ok = true;
                dispose();
            }
        });
    }

    @Override
    public String getModuleCode() {
        return module_code;
    }
}
