/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EmpOutVirtualDeptDlg.java
 *
 * Created on 2009-2-16, 15:52:03
 */
package org.jhrcore.client.personnel;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import org.jhrcore.comm.HrLog;
import org.jhrcore.client.UserContext;
import org.jhrcore.entity.DeptCode;
import org.jhrcore.entity.VirtualDeptPersonLog;
import org.jhrcore.entity.salary.ValidateSQLResult;
import org.jhrcore.iservice.impl.RSImpl;
import org.jhrcore.msg.emp.EmpMngMsg;
import org.jhrcore.ui.BeanPanel;
import org.jhrcore.ui.action.CloseAction;
import org.jhrcore.ui.task.IModuleCode;
import org.jhrcore.util.MsgUtil;

/**
 *
 * @author DB2INST3
 */
public class EmpOutVirtualDeptDlg extends javax.swing.JDialog implements IModuleCode {

    private BeanPanel beanPanel = new BeanPanel();
    private List person_list;
    private VirtualDeptPersonLog vdpLog = new VirtualDeptPersonLog();
    private DeptCode virtual_dept;
    private boolean out_flag = false;
    private HrLog log = new HrLog("EmpMng.将当前选中人员移出虚拟部门");
    private String module_code = "EmpMng.mi_virtualDeptOut";

    public boolean isOut_flag() {
        return out_flag;
    }

    public EmpOutVirtualDeptDlg() {
        super();
        this.setTitle("将当前选中人员移出虚拟部门");
        initComponents();
        initOthers();
        setupEvents();
    }

    /** Creates new form EmpOutVirtualDeptDlg */
    public EmpOutVirtualDeptDlg(List person_list, DeptCode virtual_dept) {
        super();
        this.setTitle("将当前选中人员移出虚拟部门");
        this.person_list = person_list;
        this.virtual_dept = virtual_dept;
        initComponents();
        initOthers();
        setupEvents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnOk = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);

        pnlMain.setLayout(new java.awt.BorderLayout());

        btnOk.setText("确定");

        btnCancel.setText("取消");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addComponent(btnOk)
                .addGap(27, 27, 27)
                .addComponent(btnCancel)
                .addGap(33, 33, 33))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnOk))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOk;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pnlMain;
    // End of variables declaration//GEN-END:variables

    private void initOthers() {
        vdpLog.setRemove_date(new Date());
        vdpLog.setPerson_code(UserContext.person_code);
        vdpLog.setDeptCode(virtual_dept);
        List<String> fields = new ArrayList<String>();
        fields.add("remove_date");
        fields.add("remove_reason");
        beanPanel.setBean(vdpLog);
        beanPanel.setFields(fields);
        beanPanel.setEditable(true);
        beanPanel.setColumns(1);
        beanPanel.bind();
        pnlMain.add(beanPanel, BorderLayout.CENTER);
    }

    private void setupEvents() {
        btnOk.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                log.info(e);
                if (outVirtualDept()) {
                    out_flag = true;
                    dispose();
                }
            }
        });
        CloseAction.doCloseAction(btnCancel);
    }

    private boolean outVirtualDept() {
        ValidateSQLResult result = RSImpl.outVirtualDept(person_list, vdpLog);
        if (result.getResult() == 0) {
            MsgUtil.showInfoMsg(EmpMngMsg.msg030);
            log.info("移除成功");
            return true;
        } else {
            MsgUtil.showHRSaveErrorMsg(result);
            log.info("移除失败");
            return false;
        }
    }

    @Override
    public String getModuleCode() {
        return module_code;
    }
}
