/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.jhrcore.client.ecard.ui;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import org.jhrcore.client.CommUtil;
import org.jhrcore.entity.ecard.Ecard;
import org.jhrcore.entity.salary.ValidateSQLResult;
import org.jhrcore.msg.CommMsg;
import org.jhrcore.ui.BeanPanel;
import org.jhrcore.ui.ModelFrame;
import org.jhrcore.util.MsgUtil;
import org.jhrcore.util.UtilTool;

/**
 *
 * @author Administrator
 */
public class AddEcardPanel extends javax.swing.JPanel {

    private BeanPanel beanPanel = new BeanPanel();
    private Ecard ecard;

    public AddEcardPanel() {
        initComponents();
        initOthers();
        setupEvents();
    }

    private void initOthers() {
        bPanel.add(new JScrollPane(beanPanel), BorderLayout.CENTER);
        ecard = (Ecard) UtilTool.createUIDEntity(Ecard.class);
        beanPanel.setBean(ecard);
        beanPanel.setEditable(true);
        beanPanel.bind();
        
    }

    private void setupEvents() {
        btnSave.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                ValidateSQLResult result = CommUtil.saveEntity(ecard);
                if (result.getResult() == 0) {
                    MsgUtil.showInfoMsg(CommMsg.SAVESUCCESS_MESSAGE);
                    if (cb_continue.isSelected()) {
                        ecard = (Ecard) UtilTool.createUIDEntity(Ecard.class);
                        beanPanel.setBean(ecard);
                        beanPanel.setEditable(true);
                        beanPanel.bind();
                    } else {
                        ModelFrame.close((ModelFrame) JOptionPane.getFrameForComponent(btnClose));
                    }
                } else {
                    MsgUtil.showHRSaveErrorMsg(result);
                }
            }
        });
        btnClose.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                ModelFrame.close((ModelFrame) JOptionPane.getFrameForComponent(btnClose));
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bPanel = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        cb_continue = new javax.swing.JCheckBox();

        bPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("基本信息"));
        bPanel.setLayout(new java.awt.BorderLayout());

        btnSave.setText("保存");

        btnClose.setText("关闭");

        cb_continue.setText("保存后继续添加");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cb_continue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addGap(33, 33, 33)
                .addComponent(btnClose)
                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnClose)
                    .addComponent(cb_continue))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bPanel;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox cb_continue;
    // End of variables declaration//GEN-END:variables
}
