/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.jhrcore.client.ecard.ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import org.jhrcore.entity.salary.ValidateSQLResult;
import org.jhrcore.iservice.impl.EcardImpl;
import org.jhrcore.ui.ContextManager;
import org.jhrcore.ui.ModelFrame;
import org.jhrcore.util.DateUtil;
import org.jhrcore.util.MsgUtil;

/**
 *
 * @author Jane
 */
public class CalcEcardRuPanel extends javax.swing.JPanel {

    private CardSelectDlg dlg;
    private List<String> select_keys = new ArrayList<String>();
    private String calcType = "hk";

    public CalcEcardRuPanel() {
        initComponents();
        initOthers();
        setupEvents();
    }

    public CalcEcardRuPanel(String calcType) {
        initComponents();
        this.calcType = calcType;
        initOthers();
        setupEvents();
    }

    private void initOthers() {
        btnSelect.setVisible(false);
    }

    private void setupEvents() {
        cb_state.addItemListener(new ItemListener() {

            @Override
            public void itemStateChanged(ItemEvent e) {
                btnSelect.setVisible(false);
                if ("指定卡".equals(cb_state.getSelectedItem().toString())) {
                    btnSelect.setVisible(true);
                }
            }
        });
        btnOk.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                if (DateUtil.check_pay_month(tf_ym.getText())) {
                    JOptionPane.showMessageDialog(null, "请输入正确年月");
                    return;
                }
                ValidateSQLResult result = null;
                if ("hk".equals(calcType)) {
                    result = EcardImpl.calcHuiKuan(tf_ym.getText(), cb_state.getSelectedItem().toString(), select_keys);
                } else if ("xf".equals(calcType)) {
                    result = EcardImpl.calcXiaoFei(tf_ym.getText(), cb_state.getSelectedItem().toString(), select_keys);
                }
                if (result.getResult() == 0) {
                    JOptionPane.showMessageDialog(null, "生成数据成功");
                    ModelFrame.close();
                } else {
                    MsgUtil.showHRSaveErrorMsg(result);
                }

            }
        });
        btnCancel.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                ModelFrame.close();
            }
        });
        btnSelect.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                if (dlg == null) {
                    dlg = new CardSelectDlg();
                }
                dlg.setTitle("选择信用卡");
                ContextManager.locateOnMainScreenCenter(dlg);
                dlg.setVisible(true);
                if (dlg.isOk()) {
                    select_keys.clear();
                    select_keys.addAll(dlg.getSelectKeys());
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tf_ym = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cb_state = new javax.swing.JComboBox();
        btnSelect = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        jLabel1.setText("年   月：");

        tf_ym.setText("201601");

        jLabel2.setText("信用卡：");

        cb_state.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "已激活", "已停止", "所有卡", "指定卡" }));

        btnSelect.setText("选择信用卡");

        btnOk.setText("生成");

        btnCancel.setText("取消");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_ym)
                            .addComponent(cb_state, 0, 173, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSelect))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(btnOk)
                        .addGap(61, 61, 61)
                        .addComponent(btnCancel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_ym, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_state, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelect))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk)
                    .addComponent(btnCancel))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnSelect;
    private javax.swing.JComboBox cb_state;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField tf_ym;
    // End of variables declaration//GEN-END:variables
}
