/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.jhrcore.client.ecard.ui;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import org.jhrcore.client.CommUtil;
import org.jhrcore.entity.ecard.Ecard_chu;
import org.jhrcore.entity.ecard.Epos;
import org.jhrcore.entity.salary.ValidateSQLResult;
import org.jhrcore.msg.CommMsg;
import org.jhrcore.ui.BeanPanel;
import org.jhrcore.ui.ContextManager;
import org.jhrcore.ui.ModelFrame;
import org.jhrcore.util.MsgUtil;

/**
 *
 * @author Administrator
 */
public class EditChuPanel extends javax.swing.JPanel {

    private BeanPanel beanPanel = new BeanPanel();
    private Object curObj;
    private EposSelectDlg dlg;

    public EditChuPanel() {
        initComponents();
        initOthers();
        setupEvents();
    }
    
    public EditChuPanel(Object obj) {
        initComponents();
        this.curObj = obj;
        initOthers();
        setupEvents();
    }

    private void initOthers() {
        bPanel.add(new JScrollPane(beanPanel), BorderLayout.CENTER);
        beanPanel.setBean(curObj);
        beanPanel.setEditable(true);
        beanPanel.bind();
        
    }

    private void setupEvents() {
        btnFl.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                if(dlg == null){
                    dlg = new EposSelectDlg();
                }
                dlg.setIsOk();
                dlg.setTitle("选择Pos机");
                ContextManager.locateOnMainScreenCenter(dlg);
                dlg.setVisible(true);
                if(dlg.isOk()){
                    if(dlg.getSelectObject() != null){
                        Epos tempPos = dlg.getSelectObject();
                        Ecard_chu chu = (Ecard_chu) curObj;
                        chu.setChu_fl(tempPos.getEpos_fei());
                        chu.setChu_item(tempPos.getEpos_item());
                        chu.setEpos_code(tempPos.getEpos_code());
                        chu.setEpos_name(tempPos.getEpos_name());
                        beanPanel.bind();
                    }
                }
            }
        });
        btnSave.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                ValidateSQLResult result = CommUtil.updateEntity(beanPanel.getBean());
                if (result.getResult() == 0) {
                    MsgUtil.showInfoMsg(CommMsg.SAVESUCCESS_MESSAGE);
                    ModelFrame.close((ModelFrame) JOptionPane.getFrameForComponent(btnClose));
                } else {
                    MsgUtil.showHRSaveErrorMsg(result);
                }
            }
        });
        btnClose.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                ModelFrame.close((ModelFrame) JOptionPane.getFrameForComponent(btnClose));
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bPanel = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        btnFl = new javax.swing.JButton();

        bPanel.setLayout(new java.awt.BorderLayout());

        btnSave.setText("保存");

        btnClose.setText("关闭");

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btnFl.setText("设置费率");
        btnFl.setFocusable(false);
        btnFl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFl.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnFl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(213, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addGap(33, 33, 33)
                .addComponent(btnClose)
                .addGap(67, 67, 67))
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnClose))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bPanel;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnFl;
    private javax.swing.JButton btnSave;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
