/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddPhoneUserPnl.java
 *
 * Created on 2013-8-14, 16:59:59
 */
package org.jhrcore.client.system.comm;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import javax.swing.JOptionPane;
import org.jhrcore.client.CommUtil;
import org.jhrcore.client.UserContext;
import org.jhrcore.entity.A01PassWord;
import org.jhrcore.entity.CommMap;
import org.jhrcore.entity.salary.ValidateSQLResult;
import org.jhrcore.iservice.impl.SysImpl;
import org.jhrcore.ui.StepWorkUserSelectPanel;
import org.jhrcore.ui.action.CloseAction;
import org.jhrcore.ui.listener.IPickCycListener;
import org.jhrcore.ui.listener.IPickWindowCloseListener;
import org.jhrcore.util.MsgUtil;

/**
 *
 * @author Administrator
 */
public class AddCommMapUserPnl extends javax.swing.JPanel {

    /** Creates new form AddPhoneUserPnl */
    private StepWorkUserSelectPanel user_select_pnl;
    private CommMap cm;
    private List<IPickWindowCloseListener> list_users = new ArrayList();

    public AddCommMapUserPnl(CommMap cm) {
        initComponents();
        this.cm = cm;
        initOthers();
        setUpEvent();
    }

    public void addPickWindowCloseListener(IPickWindowCloseListener user) {
        list_users.add(user);
    }

    public void delPickWindowCloseListener(IPickWindowCloseListener user) {
        list_users.remove(user);
    }

    private void initOthers() {
        user_select_pnl = new StepWorkUserSelectPanel();
        String sql = "select aw.a01PassWord_key from CommMap s,RoleA01 ra,A01PassWord aw where  aw.a01PassWord_key=ra.a01PassWord_key and ra.rolea01_key=s.user_key and s.map_key='"
                + cm.getMap_key() + "'";
        List<String> keys = (List<String>) CommUtil.selectSQL(sql);
        HashSet<String> hash_keys = new HashSet<String>();
        hash_keys.addAll(keys);
        user_select_pnl.buildTree("员工", hash_keys);
        userPanel.setLayout(new BorderLayout());
        userPanel.add(user_select_pnl, BorderLayout.CENTER);
    }

    private void setUpEvent() {
        btnSave.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                List<A01PassWord> list = user_select_pnl.getFTable().getSelectObjects();
                List<String> keys = new ArrayList<String>();
                for (A01PassWord pw : list) {
                    keys.add(pw.getA01PassWord_key());
                }
                List<String> roleA01_keys = (List<String>) CommUtil.selectSQL("select roleA01_key from RoleA01 where a01PassWord_key in", keys);
                cm.setC_user_key(UserContext.rolea01_key);
                cm.setC_user(UserContext.getCurPerson());
                ValidateSQLResult result = SysImpl.saveUsers(roleA01_keys, cm);
                if (result.getResult() == 0) {
                    for (IPickWindowCloseListener user : list_users) {
                        user.pickClose();
                    }
                    user_select_pnl.getFTable().deleteSelectedRows();
                    JOptionPane.showMessageDialog(null, "添加成功！");
                } else {
                    MsgUtil.showErrorMsg(result.getMsg());
                }
            }
        });
        CloseAction.doCloseAction(btnColse);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userPanel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnColse = new javax.swing.JButton();

        javax.swing.GroupLayout userPanelLayout = new javax.swing.GroupLayout(userPanel);
        userPanel.setLayout(userPanelLayout);
        userPanelLayout.setHorizontalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 437, Short.MAX_VALUE)
        );
        userPanelLayout.setVerticalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 336, Short.MAX_VALUE)
        );

        btnSave.setText("保存");

        btnColse.setText("关闭");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(287, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addGap(18, 18, 18)
                .addComponent(btnColse)
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnColse))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
            .addComponent(userPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(userPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnColse;
    private javax.swing.JButton btnSave;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel userPanel;
    // End of variables declaration//GEN-END:variables
}
