/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EcardPosPanel.java
 *
 * Created on 2012-3-6, 9:35:08
 */
package org.jhrcore.client.ecard;

import com.foundercy.pf.control.listener.IPickColumnSumListener;
import com.foundercy.pf.control.listener.IPickFieldOrderListener;
import com.foundercy.pf.control.listener.IPickFieldSetListener;
import com.foundercy.pf.control.listener.IPickQueryExListener;
import com.foundercy.pf.control.table.FTable;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import org.jdesktop.beansbinding.AutoBinding;
import org.jdesktop.beansbinding.Binding;
import org.jdesktop.swingbinding.SwingBindings;
import org.jhrcore.client.CommUtil;
import org.jhrcore.util.DbUtil;
import org.jhrcore.util.SysUtil;
import org.jhrcore.client.UserContext;
import org.jhrcore.client.ecard.ui.AddEposPanel;
import org.jhrcore.util.PublicUtil;
import org.jhrcore.entity.base.TempFieldInfo;
import org.jhrcore.entity.ecard.Epos;
import org.jhrcore.entity.query.QueryScheme;
import org.jhrcore.entity.salary.ValidateSQLResult;
import org.jhrcore.entity.showstyle.ShowScheme;
import org.jhrcore.msg.CommMsg;
import org.jhrcore.rebuild.EntityBuilder;
import org.jhrcore.ui.BeanPanel;
import org.jhrcore.ui.ContextManager;
import org.jhrcore.ui.ModelFrame;
import org.jhrcore.ui.task.IModulePanel;
import org.jhrcore.ui.listener.CommEditAction;
import org.jhrcore.ui.listener.IPickWindowCloseListener;
import org.jhrcore.util.ComponentUtil;
import org.jhrcore.util.ImageUtil;
import org.jhrcore.util.MsgUtil;

/**
 *
 * @author admin
 */
public class EcardPosPanel extends javax.swing.JPanel implements IModulePanel {

    private JButton btnAdd = new JButton("新增");
    private JButton btnEdit = new JButton("编辑");
    private JButton btnView = new JButton("浏览");
    private JButton btnSave = new JButton("保存");
    private JButton btnCancel = new JButton("取消");
    private JButton btnDel = new JButton("删除");
    private JButton btnTool = new JButton("工具");
    private JLabel jLabel7 = new JLabel(" 查找：");
    private JTextField comBoxSearch = new JTextField();
    private JCheckBox chbCurColumn = new JCheckBox("当前列", false);
    private JButton btnSearch = new JButton("", ImageUtil.getSearchIcon());
    private JMenu mEditWay = new JMenu("编辑方式");
    private JMenuItem miCardEdit = new JMenuItem("卡片编辑");
    private JMenuItem miTableEdit = new JMenuItem("网格编辑");
    private JMenuItem miExport = new JMenuItem("导出Excel");
    private List pay_system_list = new ArrayList();
    private JPopupMenu menu = new JPopupMenu();
    private FTable ftable;
    private List<TempFieldInfo> all_infos = new ArrayList<TempFieldInfo>();
    private List<TempFieldInfo> default_infos = new ArrayList<TempFieldInfo>();
    private List<TempFieldInfo> default_orders = new ArrayList<TempFieldInfo>();
    private String order_sql = "epos_code";
    private Object curEpos = null;
    private BeanPanel beanPanel = new BeanPanel();
    private boolean editable = false;
    private boolean editStyle = false;//false:网格；true：卡片
    public static final String module_code = "EposMng";
    private String sum_sql;
    private Binding cb_binding;

    /**
     * Creates new form EcardPosPanel
     */
    public EcardPosPanel() {
        initComponents();
        initOthers();
        setupEvents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolBar = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        cb_fl = new javax.swing.JComboBox();
        jtpMain = new javax.swing.JTabbedPane();
        jspRight = new javax.swing.JSplitPane();
        pnlTable = new javax.swing.JPanel();
        pnlCard = new javax.swing.JPanel();

        toolBar.setFloatable(false);
        toolBar.setRollover(true);
        toolBar.setMaximumSize(new java.awt.Dimension(1240, 24));
        toolBar.setMinimumSize(new java.awt.Dimension(106, 24));
        toolBar.setPreferredSize(new java.awt.Dimension(106, 24));

        jLabel1.setText("费率：");
        toolBar.add(jLabel1);

        cb_fl.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "已激活", "已停止", "所有卡" }));
        cb_fl.setMaximumSize(new java.awt.Dimension(80, 23));
        toolBar.add(cb_fl);

        jspRight.setDividerLocation(250);
        jspRight.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jspRight.setOneTouchExpandable(true);

        pnlTable.setLayout(new java.awt.BorderLayout());
        jspRight.setTopComponent(pnlTable);

        pnlCard.setLayout(new java.awt.BorderLayout());
        jspRight.setRightComponent(pnlCard);

        jtpMain.addTab("基本信息", jspRight);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jtpMain, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(toolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtpMain, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cb_fl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSplitPane jspRight;
    private javax.swing.JTabbedPane jtpMain;
    private javax.swing.JPanel pnlCard;
    private javax.swing.JPanel pnlTable;
    private javax.swing.JToolBar toolBar;
    // End of variables declaration//GEN-END:variables

    private void initOthers() {
        bindingCb();
        initToolBar();
        ftable = new FTable(Epos.class, true, true, true, "EcardPosPanel");
        List<TempFieldInfo> shift_infos = EntityBuilder.getCommFieldInfoListOf(Epos.class, EntityBuilder.COMM_FIELD_VISIBLE);
        for (TempFieldInfo tfi : shift_infos) {
            default_infos.add(tfi);
            all_infos.add(tfi);
        }
        ftable.setAll_fields(all_infos, default_infos, default_orders, "EcardPosPanel");
        order_sql = SysUtil.getSQLOrderString(ftable.getCurOrderScheme(), order_sql, all_infos);
        ftable.setRight_allow_flag(true);
        pnlTable.add(ftable);
        pnlCard.add(new JScrollPane(beanPanel));
        beanPanel.setColumns(3);
    }
    
    private void bindingCb(){
        List flList = CommUtil.selectSQL("select distinct epos_fei from Epos");
        flList.add("所有");
        if(cb_binding == null){
            cb_binding = SwingBindings.createJComboBoxBinding(AutoBinding.UpdateStrategy.READ, flList, cb_fl);
        }else{
            cb_binding.unbind();
        }
        cb_binding.bind();
    }

    private void setupEvents() {
        cb_fl.addItemListener(new ItemListener() {

            @Override
            public void itemStateChanged(ItemEvent e) {
                fetchMainData(ftable.getCur_query_scheme(), null);
            }
        });
        ftable.addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                CommEditAction.doRowSaveAction(curEpos, editable);
                if (curEpos == ftable.getCurrentRow()) {
                    return;
                }
                curEpos = ftable.getCurrentRow();
                BeanPanel.refreshUIForTable(ftable, beanPanel, editable && editStyle);
                ContextManager.setStatusBar(ftable.getObjects().size());
            }
        });
        ftable.addPickFieldOrderListener(new IPickFieldOrderListener() {

            @Override
            public void pickOrder(ShowScheme showScheme) {
                order_sql = SysUtil.getSQLOrderString(showScheme, order_sql, all_infos);
                fetchMainData(ftable.getCur_query_scheme(), null);
            }
        });
        ftable.addPickQueryExListener(new IPickQueryExListener() {

            @Override
            public void pickQuery(QueryScheme qs) {
                fetchMainData(qs, null);
            }
        });
        ftable.addPickFieldSetListener(new IPickFieldSetListener() {

            @Override
            public void pickField(ShowScheme showScheme) {
                BeanPanel.refreshUIForTable(ftable, beanPanel, editable && editStyle);
            }
        });
        ftable.addPickColumnSumListener(new IPickColumnSumListener() {

            @Override
            public String pickSumSQL() {
                return sum_sql + "@sql";
            }
        });

        btnEdit.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                setEditState(true, editStyle);
            }
        });
        btnView.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                CommEditAction.doViewAction(curEpos, ftable, beanPanel);
                setEditState(false, editStyle);
            }
        });
        btnCancel.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                CommEditAction.doCancelAction(curEpos, ftable, beanPanel);
                setEditState(editable, editStyle);
            }
        });
        btnSave.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                CommEditAction.doSaveAction(curEpos, ftable, beanPanel);
                setEditState(editable, editStyle);
            }
        });
        btnDel.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                delObj();
            }
        });
        ActionListener search_listener = new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                doQuickSearch(comBoxSearch.getText());
            }
        };
        btnSearch.addActionListener(search_listener);
        comBoxSearch.addActionListener(search_listener);
        miExport.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                ftable.exportData();
            }
        });
        ComponentUtil.refreshJSplitPane(jspRight, "EcardPosPanel.jspRight");
        fetchMainData(null, null);

    }

    private void initToolBar() {
        toolBar.add(btnAdd);
        toolBar.add(btnEdit);
        toolBar.add(btnView);
        toolBar.add(btnSave);
        toolBar.add(btnCancel);
        toolBar.add(btnDel);
        toolBar.addSeparator();
        toolBar.add(btnTool);
        toolBar.add(jLabel7);
        toolBar.add(comBoxSearch);
        toolBar.add(btnSearch);
        toolBar.add(chbCurColumn);

        menu.add(mEditWay);
        menu.addSeparator();
        menu.add(miExport);
        mEditWay.add(miTableEdit);
        mEditWay.add(miCardEdit);
        ComponentUtil.setSize(comBoxSearch, 120, 22);
        ComponentUtil.setSize(btnSearch, 22, 22);
        btnTool.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                menu.show(btnTool, 0, 25);
            }
        });
        btnAdd.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                AddEposPanel pnl = new AddEposPanel();
                ModelFrame mf = ModelFrame.showModel(ContextManager.getMainFrame(), pnl, true, "登记Pos机", 650, 500, false);
                mf.addIPickWindowCloseListener(new IPickWindowCloseListener() {

                    @Override
                    public void pickClose() {
                        bindingCb();
                        fetchMainData(null, null);
                    }
                });
                mf.setVisible(true);
            }
        });

        miTableEdit.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                setEditState(editable, false);
            }
        });
        miCardEdit.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                setEditState(editable, true);
            }
        });

    }

    private void fetchMainData(QueryScheme qs, String s_where) {
        String state = "";
        if(cb_fl.getSelectedItem() == null){
            state = "所有";
        }else{
            state = cb_fl.getSelectedItem().toString();
        }
        ftable.setCur_query_scheme(qs);
        String sql = " from Epos where 1=1";
        if (qs != null) {
            sql += " and Epos.epos_key in(" + qs.buildSql() + ")";
        }
        if (s_where != null && !s_where.trim().equals("")) {
            sql += " and (" + s_where + ")";
        }
        if (!state.equals("所有")) {
            sql += " and epos_fei = '" + state + "'";
        }
        sum_sql = sql;
        sql = "select epos_key" + sql + " order by " + order_sql;
        PublicUtil.getProps_value().setProperty(Epos.class.getName(), "from Epos n where n.epos_key in");
        List list = CommUtil.selectSQL(DbUtil.tranSQL(sql));
        ftable.setObjects(list);
        refreshStatus();
    }

    private void doQuickSearch(String text) {
        if (text == null || text.trim().equals("")) {
            return;
        }
        text = SysUtil.getQuickSearchText(text);
        String s_where = "";
        if (chbCurColumn.isSelected()) {
            s_where = ftable.getQuickSearchSQL("Epos", text);
        } else {
            s_where = "(upper(epos_code) like '" + text + "%' or upper(ecard_name) like '" + text + "%')";
        }
        fetchMainData(ftable.getCur_query_scheme(), s_where);
    }

    private void setEditState(boolean editable, boolean editStyle) {
        this.editStyle = editStyle;
        this.editable = editable;
        ComponentUtil.setIcon(miTableEdit, editStyle ? "blank" : "editWay");
        ComponentUtil.setIcon(miCardEdit, editStyle ? "editWay" : "blank");
        btnEdit.setEnabled(UserContext.hasFunctionRight(module_code + ".btnEdit") && !editable);
        btnDel.setEnabled(UserContext.hasFunctionRight(module_code + ".btnEdit") && !editable);
        btnCancel.setEnabled(UserContext.hasFunctionRight(module_code + ".btnEdit") && editable);
        btnSave.setEnabled(UserContext.hasFunctionRight(module_code + ".btnEdit") && editable);
        btnView.setEnabled(UserContext.hasFunctionRight(module_code + ".btnEdit") && editable);
        ftable.editingStopped();
        ftable.setEditable(editable && !editStyle);
        BeanPanel.refreshUIForTable(ftable, beanPanel, editable && editStyle);
    }

    private void delObj() {
        List<String> keys = ftable.getSelectKeys();
        if (keys.isEmpty()) {
            return;
        }
        if (MsgUtil.showNotConfirmDialog(CommMsg.DEL_MESSAGE)) {
            return;
        }
        ValidateSQLResult result = CommUtil.deleteObjs("Epos", "epos_key", keys);
        if (result.getResult() == 0) {
            MsgUtil.showInfoMsg(CommMsg.DELSUCCESS_MESSAGE);
            ftable.deleteSelectedRows();
        } else {
            MsgUtil.showHRDelErrorMsg(result);
        }
    }

    @Override
    public void setFunctionRight() {
        ComponentUtil.setSysFuntion(this, module_code);
        ftable.setExportItemEnable(miExport.isEnabled());
        setEditState(false, false);
    }

    @Override
    public void pickClose() {
    }

    @Override
    public void refresh() {
        refreshStatus();
    }

    private void refreshStatus() {
        ContextManager.setStatusBar(ftable.getObjects().size());
    }

    @Override
    public String getModuleCode() {
        return module_code;
    }
}
